INSERT INTO QUESTION (TEXT, TYPE, CORRECT_ANSWER) VALUES ('How old was Naruto at end of Shippuden', 'anime', '19');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (1, '21');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (1, '19');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (1, '18');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (1, '22');

INSERT INTO QUESTION (TEXT, TYPE, CORRECT_ANSWER) VALUES ('Who is the main protagonist in Attack on Titan?', 'anime', 'Eren Yeager');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (2, 'Levi Ackerman');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (2, 'Mikasa Ackerman');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (2, 'Eren Yeager');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (2, 'Armin Arlert');

INSERT INTO QUESTION (TEXT, TYPE, CORRECT_ANSWER) VALUES ('What is the name of the pirate crew led by Monkey D. Luffy?', 'anime', 'Straw Hat Pirates');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (3, 'Blackbeard Pirates');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (3, 'Red-Haired Pirates');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (3, 'Straw Hat Pirates');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (3, 'Whitebeard Pirates');

INSERT INTO QUESTION (TEXT, TYPE, CORRECT_ANSWER) VALUES ('In Death Note, what is the Shinigami who drops the Death Note into the human world called?', 'anime', 'Ryuk');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (4, 'Rem');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (4, 'Ryuk');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (4, 'Gelus');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (4, 'Sidoh');

INSERT INTO QUESTION (TEXT, TYPE, CORRECT_ANSWER) VALUES ('What is the name of the alchemy used by Edward Elric in Fullmetal Alchemist?', 'anime', 'Alchemy');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (5, 'Transmutation');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (5, 'Alchemy');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (5, 'Equivalent Exchange');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (5, 'Philosopher Stone');

INSERT INTO QUESTION (TEXT, TYPE, CORRECT_ANSWER) VALUES ('In My Hero Academia, what is the hero name of Izuku Midoriya?', 'anime', 'Deku');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (6, 'Kacchan');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (6, 'All Might');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (6, 'Deku');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (6, 'Shoto');

INSERT INTO QUESTION (TEXT, TYPE, CORRECT_ANSWER) VALUES ('Who is the captain of the Gotei 13 6th Division in Bleach?', 'anime', 'Byakuya Kuchiki');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (7, 'Toshiro Hitsugaya');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (7, 'Byakuya Kuchiki');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (7, 'Kenpachi Zaraki');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (7, 'Sosuke Aizen');

INSERT INTO QUESTION (TEXT, TYPE, CORRECT_ANSWER) VALUES ('In Dragon Ball Z, what is the name of Goku signature attack?', 'anime', 'Kamehameha');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (8, 'Final Flash');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (8, 'Special Beam Cannon');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (8, 'Kamehameha');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (8, 'Spirit Bomb');

INSERT INTO QUESTION (TEXT, TYPE, CORRECT_ANSWER) VALUES ('Who is the main character in Cowboy Bebop?', 'anime', 'Spike Spiegel');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (9, 'Jet Black');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (9, 'Spike Spiegel');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (9, 'Faye Valentine');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (9, 'Edward Wong');

INSERT INTO QUESTION (TEXT, TYPE, CORRECT_ANSWER) VALUES ('In Sword Art Online, what is the name of the first VRMMORPG that Kirito plays?', 'anime', 'Sword Art Online');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (10, 'ALfheim Online');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (10, 'Gun Gale Online');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (10, 'Sword Art Online');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (10, 'Ordinal Scale');

INSERT INTO QUESTION (TEXT, TYPE, CORRECT_ANSWER) VALUES ('What is the name of the island where the game in No Game No Life takes place?', 'anime', 'Disboard');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (11, 'Aincrad');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (11, 'Disboard');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (11, 'Fiore');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (11, 'Magnolia');

INSERT INTO QUESTION (TEXT, TYPE, CORRECT_ANSWER) VALUES ('In Tokyo Ghoul, what kind of creature is Kaneki transformed into?', 'anime', 'Ghoul');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (12, 'Vampire');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (12, 'Ghoul');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (12, 'Werewolf');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (12, 'Zombie');

INSERT INTO QUESTION (TEXT, TYPE, CORRECT_ANSWER) VALUES ('In Fairy Tail, who is the main female protagonist?', 'anime', 'Lucy Heartfilia');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (13, 'Erza Scarlet');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (13, 'Lucy Heartfilia');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (13, 'Juvia Lockser');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (13, 'Wendy Marvell');

INSERT INTO QUESTION (TEXT, TYPE, CORRECT_ANSWER) VALUES ('In One Punch Man, what is Saitama hero name?', 'anime', 'Caped Baldy');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (14, 'Silver Fang');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (14, 'Caped Baldy');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (14, 'Atomic Samurai');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (14, 'King');

INSERT INTO QUESTION (TEXT, TYPE, CORRECT_ANSWER) VALUES ('What is the name of the school in Danganronpa?', 'anime', 'Hope Peak Academy');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (15, 'U.A. High School');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (15, 'Hope Peak Academy');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (15, 'Honnoji Academy');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (15, 'Ouran Academy');

INSERT INTO QUESTION (TEXT, TYPE, CORRECT_ANSWER) VALUES ('In Black Clover, what is the name of Asta grimoire?', 'anime', 'Five-Leaf Clover Grimoire');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (16, 'Four-Leaf Clover Grimoire');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (16, 'Five-Leaf Clover Grimoire');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (16, 'Six-Leaf Clover Grimoire');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (16, 'Three-Leaf Clover Grimoire');

INSERT INTO QUESTION (TEXT, TYPE, CORRECT_ANSWER) VALUES ('In Hunter x Hunter, who is Gon best friend?', 'anime', 'Killua Zoldyck');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (17, 'Kurapika');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (17, 'Leorio Paradinight');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (17, 'Killua Zoldyck');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (17, 'Hisoka Morow');

INSERT INTO QUESTION (TEXT, TYPE, CORRECT_ANSWER) VALUES ('In Naruto, what is the name of the Nine-Tailed Fox?', 'anime', 'Kurama');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (18, 'Shukaku');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (18, 'Matatabi');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (18, 'Kurama');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (18, 'Gyuki');

INSERT INTO QUESTION (TEXT, TYPE, CORRECT_ANSWER) VALUES ('In JoJo Bizarre Adventure, who is the first JoJo?', 'anime', 'Jonathan Joestar');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (19, 'Joseph Joestar');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (19, 'Jotaro Kujo');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (19, 'Giorno Giovanna');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (19, 'Jonathan Joestar');

INSERT INTO QUESTION (TEXT, TYPE, CORRECT_ANSWER) VALUES ('In Neon Genesis Evangelion, what is the name of the organization fighting the Angels?', 'anime', 'NERV');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (20, 'SEELE');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (20, 'NERV');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (20, 'Gendo');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (20, 'WILLE');

INSERT INTO QUESTION (TEXT, TYPE, CORRECT_ANSWER) VALUES ('In Steins;Gate, what is the main character nickname?', 'anime', 'Hououin Kyouma');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (21, 'Daru');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (21, 'Hououin Kyouma');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (21, 'Okarin');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (21, 'Mayushii');

INSERT INTO QUESTION (TEXT, TYPE, CORRECT_ANSWER) VALUES ('In Re:Zero, what is the name of the half-elf girl that Subaru loves?', 'anime', 'Emilia');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (22, 'Rem');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (22, 'Ram');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (22, 'Emilia');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (22, 'Beatrice');

INSERT INTO QUESTION (TEXT, TYPE, CORRECT_ANSWER) VALUES ('In Mob Psycho 100, what is the percentage of Mob power that causes him to go berserk?', 'anime', '100%');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (23, '90%');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (23, '100%');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (23, '80%');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (23, '70%');

INSERT INTO QUESTION (TEXT, TYPE, CORRECT_ANSWER) VALUES ('In Demon Slayer, what is the color of Tanjiro Kamado sword?', 'anime', 'Black');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (24, 'Red');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (24, 'Blue');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (24, 'Black');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (24, 'White');

INSERT INTO QUESTION (TEXT, TYPE, CORRECT_ANSWER) VALUES ('In Sword Art Online, what is the name of Kirito sister?', 'anime', 'Suguha Kirigaya');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (25, 'Asuna Yuuki');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (25, 'Suguha Kirigaya');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (25, 'Sinon');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (25, 'Leafa');

INSERT INTO QUESTION (TEXT, TYPE, CORRECT_ANSWER) VALUES ('In Hunter x Hunter, what is the main character goal?', 'anime', 'To become a Hunter');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (26, 'To find his father');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (26, 'To become a Hunter');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (26, 'To be the strongest');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (26, 'To get revenge');

INSERT INTO QUESTION (TEXT, TYPE, CORRECT_ANSWER) VALUES ('In Fullmetal Alchemist, what is Edward Elric brother name?', 'anime', 'Alphonse Elric');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (27, 'Roy Mustang');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (27, 'Maes Hughes');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (27, 'Alphonse Elric');
INSERT INTO QUESTION_OPTIONS (QUESTION_ID, OPTION) VALUES (27, 'Riza Hawkeye');


INSERT INTO APP_USER (NAME, PASSWORD, USERNAME) VALUES ('Paul Michael', '1234', 'Michael');
INSERT INTO APP_USER (NAME, PASSWORD, USERNAME) VALUES ('Paul Kingsley', '1234', 'Kingsley');
INSERT INTO APP_USER (NAME, PASSWORD, USERNAME) VALUES ('Paul Angela', '1234', 'Angela');
INSERT INTO APP_USER (NAME, PASSWORD, USERNAME) VALUES ('Jasmine', '$2a$12$ANFcNlHYC71WMImheMzCd.NqiJEVumk2.u0e7.qmOzE0PExRz80Ga', 'Jasmine');

